"default": true
"MD001": false
"MD004": false
"MD007":
  "indent": 4
"MD024": false
"MD025": false
"MD026":
  "punctuation": ".;:"
"MD029": false
"MD033": false
"MD034": false
"MD036": false
"MD040": false
"MD041": false
"MD051": false
"MD049":
  "style": "asterisk"
"MD013":
  "line_length": 999
  "code_blocks": true
  "tables": true
  "code_block_line_length": 120
  "table_line_length": 120
"MD047": true
"no-hard-tabs": false
