queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=automerge
    merge_conditions:
      - "#approved-reviews-by>1"
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}

pull_request_rules:
  - name: backport patches to v0.3.x branch
    conditions:
      - base=main
      - label=backport/0.3.x
    actions:
      backport:
        branches:
          - release/v0.3.x
