// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ethermint/types/v1/eth_account.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	types "github.com/cosmos/cosmos-sdk/x/auth/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EthAccount implements the sdk.AccountI interface and embeds an
// authtypes.BaseAccount type. It is compatible with the auth AccountKeeper.
type EthAccount struct {
	// base_account is an authtypes.BaseAccount
	*types.BaseAccount `protobuf:"bytes,1,opt,name=base_account,json=baseAccount,proto3,embedded=base_account" json:"base_account,omitempty" yaml:"base_account"`
	// code_hash is the hash calculated from the code contents
	CodeHash string `protobuf:"bytes,2,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty" yaml:"code_hash"`
}

func (m *EthAccount) Reset()      { *m = EthAccount{} }
func (*EthAccount) ProtoMessage() {}
func (*EthAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d262311d8a1b9bc2, []int{0}
}
func (m *EthAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EthAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EthAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EthAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthAccount.Merge(m, src)
}
func (m *EthAccount) XXX_Size() int {
	return m.Size()
}
func (m *EthAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_EthAccount.DiscardUnknown(m)
}

var xxx_messageInfo_EthAccount proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EthAccount)(nil), "ethermint.types.v1.EthAccount")
}

func init() {
	proto.RegisterFile("ethermint/types/v1/eth_account.proto", fileDescriptor_d262311d8a1b9bc2)
}

var fileDescriptor_d262311d8a1b9bc2 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0x02, 0x31,
	0x14, 0xc7, 0x5b, 0x07, 0x23, 0x87, 0x83, 0x39, 0x49, 0x44, 0x34, 0x2d, 0xb9, 0x38, 0x30, 0x68,
	0x9b, 0xd3, 0x8d, 0xb8, 0x78, 0x89, 0x89, 0xae, 0x8c, 0x2e, 0xd8, 0xab, 0x4d, 0x4b, 0x42, 0x29,
	0xa1, 0xe5, 0x12, 0xbe, 0x81, 0xa3, 0xa3, 0x23, 0x1f, 0xc2, 0x0f, 0x61, 0x5c, 0x64, 0x74, 0x22,
	0x06, 0x16, 0x67, 0x3e, 0x81, 0xe1, 0x5a, 0xd1, 0xc1, 0xed, 0xbd, 0xf7, 0x7f, 0xff, 0x7f, 0x7f,
	0x79, 0x8d, 0x4e, 0x84, 0x53, 0x62, 0xa4, 0x7b, 0x03, 0x47, 0xdd, 0x64, 0x28, 0x2c, 0x2d, 0x52,
	0x2a, 0x9c, 0xea, 0x32, 0xce, 0xcd, 0x78, 0xe0, 0xc8, 0x70, 0x64, 0x9c, 0x89, 0xe3, 0xcd, 0x16,
	0x29, 0xb7, 0x48, 0x91, 0x36, 0x10, 0x37, 0x56, 0x1b, 0x4b, 0xd9, 0xd8, 0x29, 0x5a, 0xa4, 0xb9,
	0x70, 0x2c, 0x2d, 0x1b, 0xef, 0x69, 0x1c, 0x7a, 0xbd, 0x5b, 0x76, 0xd4, 0x37, 0x41, 0xaa, 0x49,
	0x23, 0x8d, 0x9f, 0xaf, 0xab, 0x30, 0x3d, 0x08, 0x81, 0xda, 0xca, 0x35, 0x85, 0xb6, 0xd2, 0x0b,
	0xc9, 0x3b, 0x8c, 0xa2, 0x6b, 0xa7, 0xae, 0x3c, 0x52, 0x7c, 0x1f, 0xed, 0xe6, 0xcc, 0x8a, 0x1f,
	0xc4, 0x3a, 0x6c, 0xc2, 0x56, 0xf5, 0xbc, 0x49, 0xc2, 0x13, 0x25, 0x42, 0xe0, 0x21, 0x19, 0xb3,
	0x22, 0xf8, 0xb2, 0xa3, 0xd9, 0x1c, 0xc3, 0xd5, 0x1c, 0xef, 0x4f, 0x98, 0xee, 0xb7, 0x93, 0xbf,
	0x19, 0x49, 0xa7, 0x9a, 0xff, 0x6e, 0xc6, 0x69, 0x54, 0xe1, 0xe6, 0x41, 0x74, 0x15, 0xb3, 0xaa,
	0xbe, 0xd5, 0x84, 0xad, 0x4a, 0x56, 0x5b, 0xcd, 0xf1, 0x9e, 0x37, 0x6e, 0xa4, 0xa4, 0xb3, 0xb3,
	0xae, 0x6f, 0x98, 0x55, 0xed, 0xd3, 0xc7, 0x29, 0x06, 0xcf, 0x53, 0x0c, 0xbe, 0xa6, 0x18, 0xbc,
	0xbd, 0x9c, 0x1d, 0xff, 0x47, 0x13, 0xf2, 0x6f, 0xb3, 0xcb, 0xd7, 0x05, 0x82, 0xb3, 0x05, 0x82,
	0x9f, 0x0b, 0x04, 0x9f, 0x96, 0x08, 0xcc, 0x96, 0x08, 0x7c, 0x2c, 0x11, 0xb8, 0x4b, 0x64, 0xcf,
	0xa9, 0x71, 0x4e, 0xb8, 0xd1, 0xe1, 0x66, 0x54, 0x14, 0x9a, 0xf6, 0x85, 0x64, 0x7c, 0xe2, 0xbf,
	0x28, 0xdf, 0x2e, 0xcf, 0x72, 0xf1, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x48, 0x1c, 0x26, 0xd9, 0xbc,
	0x01, 0x00, 0x00,
}

func (m *EthAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EthAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EthAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CodeHash) > 0 {
		i -= len(m.CodeHash)
		copy(dAtA[i:], m.CodeHash)
		i = encodeVarintEthAccount(dAtA, i, uint64(len(m.CodeHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.BaseAccount != nil {
		{
			size, err := m.BaseAccount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEthAccount(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEthAccount(dAtA []byte, offset int, v uint64) int {
	offset -= sovEthAccount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EthAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BaseAccount != nil {
		l = m.BaseAccount.Size()
		n += 1 + l + sovEthAccount(uint64(l))
	}
	l = len(m.CodeHash)
	if l > 0 {
		n += 1 + l + sovEthAccount(uint64(l))
	}
	return n
}

func sovEthAccount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEthAccount(x uint64) (n int) {
	return sovEthAccount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EthAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEthAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EthAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EthAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAccount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BaseAccount == nil {
				m.BaseAccount = &types.BaseAccount{}
			}
			if err := m.BaseAccount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEthAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEthAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEthAccount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEthAccount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEthAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEthAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEthAccount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEthAccount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEthAccount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEthAccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEthAccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEthAccount = fmt.Errorf("proto: unexpected end of group")
)
