name: Lint
# Lint runs golangci-lint over the entire Cosmos EVM repository
# This workflow runs on every pull request and push to main

on:
  merge_group:
  pull_request:


permissions: read-all

jobs:
  golangci:
    name: Run golangci-lint
    runs-on: depot-ubuntu-24.04-8
    timeout-minutes: 15
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Determine diff so we don't lint when no Go files are changed
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            *.toml

      - name: Run linting
        if: env.GIT_DIFF
        id: lint_long
        run: |
          make lint-go

  markdown-lint:
    name: Run markdown-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.md
      - uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.yml
          ignore_path: .markdownlintignore
        # Check only if there are differences in the source code
        if: env.GIT_DIFF
